# Generated by Django 5.1.4 on 2025-09-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='disney_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='hulu_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='netflix_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='prime_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
